# Generated by Django 5.2.3 on 2025-06-15 13:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
